// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// --dart-define=API_KEY=...
const apiKey = const String.fromEnvironment('API_KEY');

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:639837130715:web:5b692ad1e548f46e1621fe',
    messagingSenderId: '639837130715',
    projectId: 'colours-of-wine',
    authDomain: 'colours-of-wine.firebaseapp.com',
    storageBucket: 'colours-of-wine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:639837130715:android:3ea26c0fd16e253b1621fe',
    messagingSenderId: '639837130715',
    projectId: 'colours-of-wine',
    storageBucket: 'colours-of-wine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:639837130715:ios:45500d7ea990c3a41621fe',
    messagingSenderId: '639837130715',
    projectId: 'colours-of-wine',
    storageBucket: 'colours-of-wine.firebasestorage.app',
    iosBundleId: 'com.example.coloursOfWine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:639837130715:ios:45500d7ea990c3a41621fe',
    messagingSenderId: '639837130715',
    projectId: 'colours-of-wine',
    storageBucket: 'colours-of-wine.firebasestorage.app',
    iosBundleId: 'com.example.coloursOfWine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: apiKey,
    appId: '1:639837130715:web:d142ca9d442c7e521621fe',
    messagingSenderId: '639837130715',
    projectId: 'colours-of-wine',
    authDomain: 'colours-of-wine.firebaseapp.com',
    storageBucket: 'colours-of-wine.firebasestorage.app',
  );
}
